<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginpkContextCMSSlot extends BasepkContextCMSSlot
{
  // By default, the editor for a slot is accessed by double-clicking
  // on an outlined normal view of the slot. That's not appropriate
  // for some custom slot types. Say so by overriding this function
  // in your slot's model subclass and returning false. Then you'll
  // need to implement opening the editor yourself. You can do that
  // in your _normal_view.php by testing $editable and outputting
  // button_to("Edit", $showEditorJS) or similar if it is true.
  // showEditorJS contains ready-to-go jQuery code to hide the
  // normal view and display the editor view.
  //
  // The return value of this method becomes the default setting of
  // the outline_editable option, which can still be overridden
  // manually.

  public function isOutlineEditable()
  {
    return true;
  }

  // You should return a reasonable plaintext representation of your
  // slot's contents for search indexing purposes. A media slot
  // would return the title and description of its contents.

  public function getSearchText()
  {
    return '';
  }
}
