<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginpkContextCMSAreaTable extends Doctrine_Table
{
  static public function retrieveOrCreateByPageIdAndName(
    $pageId, $name)
  {
    $culture = pkContextCMSTools::getUserCulture();
    $area = Doctrine_Query::create()->
      from('pkContextCMSArea a')->
      where('a.page_id = ? AND a.name = ? AND a.culture = ?',
        array($pageId, $name, $culture))->
      fetchOne();
    if ($area)
    {
      return $area;
    }
    $area = new pkContextCMSArea();
    $area->page_id = $pageId;
    $area->name = $name;
    $area->culture = $culture;
    return $area;
  }
}
