<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginpkContextCMSRichTextSlot extends BasepkContextCMSRichTextSlot
{
  public function getSearchText()
  {
    // Convert from HTML to plaintext before indexing by Lucene
    return strip_tags($this->value);
  }
}
