<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginpkContextCMSSlideshowSlot extends BasepkContextCMSSlideshowSlot
{
  public function isOutlineEditable()
  {
    // We have an edit button and don't use an in-place editor
    return false;
  }
}
